# Generated by Django 6.0.4 on 2026-04-29 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='ocorrencias/fotos/')),
                ('date_send', models.DateTimeField(auto_now_add=True)),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_da_ocorrencia', to='Ocorrencias.ocorrencia')),
            ],
        ),
    ]
