# Generated by Django 6.0.4 on 2026-04-29 14:24

import django.db.models.deletion
import localflavor.br.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('trade_name', models.CharField(max_length=100)),
                ('cnpj', localflavor.br.models.BRCNPJField(max_length=18, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cep', localflavor.br.models.BRPostalCodeField(max_length=9)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
