# Generated by Django 4.2.30 on 2026-05-26 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Secretaria', '0001_initial'),
        ('Prefeitura', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSecretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='Secretaria.secretaria')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_secretaria', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminPrefeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('prefeitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='Prefeitura.prefeitura')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_prefeitura', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
