# Generated by Django 4.2.30 on 2026-10-08 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=30, unique=True)),
                ('tipo_acao', models.CharField(choices=[('CR', 'Criação'), ('EN', 'Encaminhamento'), ('ST', 'Mudança de status'), ('OB', 'Observação')], max_length=2)),
                ('visibilidade', models.CharField(choices=[('PU', 'Pública'), ('IN', 'Interna')], default='PU', max_length=2)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SequenciaProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(max_length=6)),
                ('sigla', models.CharField(max_length=3)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='protocolo',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='sequenciaprotocolo',
            constraint=models.UniqueConstraint(fields=('competencia', 'sigla'), name='unique_sequencia_protocolo'),
        ),
        migrations.AddField(
            model_name='registroprotocolo',
            name='ocorrencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_protocolo', to='Ocorrencias.ocorrencia'),
        ),
        migrations.AddField(
            model_name='registroprotocolo',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_protocolo', to=settings.AUTH_USER_MODEL),
        ),
    ]
