# Generated by Django 4.2.30 on 2026-10-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secretaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretaria',
            name='sigla',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
